logoutput: stderr

internal: 0.0.0.0 port = 1080
external: wg0

# no auth
socksmethod: username
clientmethod: none

user.notprivileged: nobody

# Who can connect
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error
}

# where we can go
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    socksmethod: username
    command: bind connect udpassociate
    log: error disconnect
}
